baseURL = 'https://abstractionjackson.com'
languageCode = 'en-us'
title = 'Jackson Galan | Portfolio'
theme = 'saturday'
summaryLength = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/posts/projects'
weight = 20

[[menus.main]]
name = 'Resume'
pageRef = '/resume.pdf'
weight = 30
